### ISSUE TITLE
[BUG] segfault when using mlx_create_cursor

### ISSUE THREAD

**Issue by xApologize** [codam-coding-college/MLX42#72]
**Describe the bug**
When i try to change the cursor in this small project, it segfaults when trying to do mlx_create_cursor

**To Reproduce**

```c
#include <stdio.h>
#include "MLX42/MLX42.h"

int32_t	main(void)
{
	mlx_t	*mlx;

	mlx = mlx_init(500, 500, "MLX42", true);
	if (!mlx)
		return (0);
	printf("ok\n");
	mlx_texture_t* tex = mlx_load_png("./GitHub-Mark-32px.png");
	printf("ok1\n");
	mlx_create_cursor(tex);
	printf("ok2\n");
	mlx_loop(mlx);
	mlx_terminate(mlx);
	return (1);
}
```

**Screenshots**
<img width="570" alt="Screen Shot 2023-01-20 at 1 36 46 PM" src="https://user-images.githubusercontent.com/104783397/213779471-31931ebd-1552-49a4-9778-5888bc127394.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Catalina 10.15.7

**Additional context**
![GitHub-Mark-32px](https://user-images.githubusercontent.com/104783397/213778722-26e057bb-bf48-4a12-85a0-e40aec26f46b.png) the png i use.

**Comment by W2Wizard** [comment]
Ah alrighty. This is due to one of my commits where I changed the layout of the `mlx_image_t` struct to keep the pixel buffer at the bottom. I forgot that it was on purpose that it wasn't as I was using it to perfectly map it to a `GLFWImage`.

Will fix this tomorrow and push the fix 👍 

Thank you for reporting this!
